[theme]
base="dark"
primaryColor="#ff4d00"
backgroundColor="#006633"
secondaryBackgroundColor="#000000"


[server]

# The port where the server will listen for client and browser connections.
# Default: 8501
port = 80

# Enables support for Cross-Origin Request Sharing, for added security.
# Default: true
enableCORS = false

[browser]
# Internet address of the server that the browser should connect to. Can be IP address or DNS name.
# Default: 'localhost'
serverAddress = "0.0.0.0"

# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = true

# Port that the browser should use to connect to the server when in liveSave mode.
# Default: whatever value is set in server.port.
serverPort = 80
